### ISSUE TITLE
syntax highlight messed up after a point 

### ISSUE THREAD

**Issue by timotheecour** [h3rald/nimline#11]
reduced from /Users/timothee/git_clone/nim/Nim/lib/pure/hashes.nim

```nim
proc hashData() =
  when false:
    asm """`baz`;"""

proc hash(): Hash =
  when false:
    asm """
    """
  else:
    result = 0

proc foo() = discard
```

![image](https://user-images.githubusercontent.com/2194784/44072096-bc5fe272-9f41-11e8-8ecb-a4ca4d643880.png)

**Comment by h3rald** [comment]
I am not sure I understand... nimline does not provide syntax highlighting or multi line editing... did you mean to open this on another project?

**Comment by timotheecour** [comment]
sorry!! confused it with nimlime again... ; moved to https://github.com/Varriount/NimLime/issues/104
