### ISSUE TITLE
Windows 7 cmd.exe: Unhandled exception when going to the start of the line

### ISSUE THREAD

**Issue by Esgorhannoth** [h3rald/nimline#8]
I encountered this problem whille working in ```min``` REPL, but I suppose the issue belongs here.

Steps to reproduce:
1. Open cmd.exe or powershell
2. Enter min REPL ```min -i``` (in my case)
3. Type a line long enough so that it goes to the next line
4. Press ```Ctrl-a``` once or ```Backspace``` enough times to go to the previous line
```
min.nim(349)             min
min.nim(252)             minRepl
min.nim(240)             minRepl
nimline.nim(493)         readLine
nimline.nim(357)         :anonymous
nimline.nim(206)         goToStart
terminal.nim(383)        cursorBackward
terminal.nim(191)        setCursorPos
oserr.nim(110)           raiseOSError
Error: unhandled exception: ╨Я╨░╤А╨░╨╝╨╡╤В╤А ╨╖╨░╨┤╨░╨╜ ╨╜╨╡╨▓╨╡╤А╨╜╨╛.
 [OSError]
```
Those alien letters mean: "Bad parameter", if translated. I suggest wrapping two last lines in ```goToStart``` with ```try...except``` block.

**Comment by h3rald** [comment]
Thanks a lot! Yep, that's the right place, I'll take a look this weekend if I get a chance.

**Comment by h3rald** [comment]
Seems to be windows specific, I can't reproduce it on macOS. Will have to look into it on a Windows computer. 

...pull requests welcome of course!

**Comment by Esgorhannoth** [comment]
I've tracked it down to this line in Nim's library:
https://github.com/nim-lang/Nim/blob/devel/lib/pure/terminal.nim#L382
It decrements cursor's X position by the provided ```count``` and later (at [L186](https://github.com/nim-lang/Nim/blob/devel/lib/pure/terminal.nim#L186)) just calls Windows API to set it, raising exception on (obvious in this case) failure.

I'm not well versed in Nim to propose something to Nim's repository, so I just suggest adding ```try...except``` to ```goToStart``` like this:
```nim
proc goToStart*(ed: var LineEditor) =
  if ed.line.position <= 0:
    return
  try:
    stdout.cursorBackward(ed.line.position)
    ed.line.position = 0
  except:
    discard
```
It won't move the cursor, but it won't crash the app either.

**Comment by h3rald** [comment]
Thanks! Well, your changes don't hurt so... they're in. Please let me know if this is enough to fix this issue!

**Comment by Esgorhannoth** [comment]
Yep, seems to work. At least no crashes for now. :sweat_smile:
